In [50]:
import pandas as pd
import numpy as np

matches = pd.read_csv("../Data/raw/WorldCupMatches.csv")

matches.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,4444.0,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,18346.0,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,24059.0,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,2549.0,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
4,1930.0,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,,23409.0,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA

In [56]:
matches.shape

(4572, 20)

In [57]:
matches.columns

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials'],
      dtype='str')

In [51]:
matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 4572 entries, 0 to 4571
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  852 non-null    float64
 1   Datetime              852 non-null    str
 2   Stage                 852 non-null    str
 3   Stadium               852 non-null    str
 4   City                  852 non-null    str
 5   Home Team Name        852 non-null    str
 6   Home Team Goals       852 non-null    float64
 7   Away Team Goals       852 non-null    float64
 8   Away Team Name        852 non-null    str
 9   Win conditions        852 non-null    str
 10  Attendance            850 non-null    float64
 11  Half-time Home Goals  852 non-null    float64
 12  Half-time Away Goals  852 non-null    float64
 13  Referee               852 non-null    str
 14  Assistant 1           852 non-null    str
 15  Assistant 2           852 non-null    str
 16  RoundID               852 non-null    float64
 17  MatchID               852 non-null    float64
 18  Home Team Initials    852 non-null    str
 19  Away Team Initials    852 non-null    str
dtypes: float64(8), str(12)
memory usage: 714.5 KB

In [52]:
# checking null values in the dataset
matches.isnull().sum()

Year                    3720
Datetime                3720
Stage                   3720
Stadium                 3720
City                    3720
Home Team Name          3720
Home Team Goals         3720
Away Team Goals         3720
Away Team Name          3720
Win conditions          3720
Attendance              3722
Half-time Home Goals    3720
Half-time Away Goals    3720
Referee                 3720
Assistant 1             3720
Assistant 2             3720
RoundID                 3720
MatchID                 3720
Home Team Initials      3720
Away Team Initials      3720
dtype: int64

In [53]:
#Checking duplicates in the dataset
matches.duplicated().sum()

np.int64(3735)

In [54]:
matches.describe()

,Year,Home Team Goals,Away Team Goals,Attendance,Half-time Home Goals,Half-time Away Goals,RoundID,MatchID
count,852.000000,852.000000,852.000000,850.000000,852.000000,852.000000,8.520000e+02,8.520000e+02
mean,1985.089202,1.811033,1.022300,45164.800000,0.708920,0.428404,1.066177e+07,6.134687e+07
std,22.448825,1.610255,1.087573,23485.249247,0.937414,0.691252,2.729613e+07,1.110572e+08
min,1930.000000,0.000000,0.000000,2000.000000,0.000000,0.000000,2.010000e+02,2.500000e+01
25%,1970.000000,1.000000,0.000000,30000.000000,0.000000,0.000000,2.620000e+02,1.188750e+03
50%,1990.000000,2.000000,1.000000,41579.500000,0.000000,0.000000,3.370000e+02,2.191000e+03
75%,2002.000000,3.000000,2.000000,61374.500000,1.000000,1.000000,2.497220e+05,4.395006e+07
max,2014.000000,10.000000,7.000000,173850.000000,6.000000,5.000000,9.741060e+07,3.001865e+08

In [58]:
#Check the unique values in the column

matches["Stage"].unique()

<StringArray>
[                 'Group 1',                  'Group 4',
                  'Group 2',                  'Group 3',
              'Semi-finals',                    'Final',
        'Preliminary round',           'Quarter-finals',
    'Match for third place',              'First round',
                  'Group 6',                  'Group B',
                  'Group A',                  'Group 5',
                  'Group C',                  'Group D',
                  'Group F',                  'Group E',
              'Round of 16',                  'Group H',
                  'Group G',              'Third place',
 'Play-off for third place',                        nan]
Length: 24, dtype: str

In [60]:
matches["Home Team Name"].unique()

<StringArray>
[                    'France',                        'USA',
                 'Yugoslavia',                    'Romania',
                  'Argentina',                      'Chile',
                    'Uruguay',                     'Brazil',
                   'Paraguay',                    'Austria',
                    'Hungary',                'Switzerland',
                     'Sweden',                    'Germany',
                      'Spain',                      'Italy',
             'Czechoslovakia',                       'Cuba',
                    'England',                 'Germany FR',
                     'Turkey',               'Soviet Union',
           'Northern Ireland',                     'Mexico',
                      'Wales',                   'Portugal',
                  'Korea DPR',                       'Peru',
                    'Belgium',                   'Bulgaria',
                  'German DR',                      'Zaire',
                     'Poland',                  'Australia',
                   'Scotland',                'Netherlands',
                      'Haiti',                    'Tunisia',
                    'Algeria',                   'Honduras',
                     'Canada',                    'Morocco',
             'Korea Republic',                       'Iraq',
                    'Denmark',   'rn">United Arab Emirates',
                 'Costa Rica',                   'Cameroon',
    'rn">Republic of Ireland',                   'Colombia',
                     'Norway',                    'Nigeria',
               'Saudi Arabia',                    'Bolivia',
                     'Russia',                     'Greece',
                    'Jamaica',               'South Africa',
                      'Japan',                    'Croatia',
                   'China PR',                    'Senegal',
                   'Slovenia',                    'Ecuador',
    'rn">Trinidad and Tobago',  'rn">Serbia and Montenegro',
                     'Angola',             'Czech Republic',
                       'Togo',                       'Iran',
              'C�te d'Ivoire',                      'Ghana',
                    'Ukraine',                     'Serbia',
                'New Zealand',                   'Slovakia',
                    'IR Iran', 'rn">Bosnia and Herzegovina',
                          nan]
Length: 79, dtype: str

In [80]:

matches["Away Team Name"].unique()

<StringArray>
[                    'Mexico',                    'Belgium',
                     'Brazil',                       'Peru',
                     'France',                    'Bolivia',
                   'Paraguay',                    'Romania',
                      'Chile',                        'USA',
                 'Yugoslavia',                  'Argentina',
                      'Egypt',                'Netherlands',
                'Switzerland',                     'Sweden',
                      'Spain',                    'Hungary',
                    'Austria',                    'Germany',
             'Czechoslovakia',          'Dutch East Indies',
                     'Norway',                     'Poland',
                       'Cuba',                      'Italy',
                    'England',                   'Scotland',
                     'Turkey',             'Korea Republic',
                 'Germany FR',                    'Uruguay',
                      'Wales',           'Northern Ireland',
               'Soviet Union',                   'Colombia',
                   'Bulgaria',                  'Korea DPR',
                   'Portugal',                     'Israel',
                    'Morocco',                'El Salvador',
                  'Australia',                      'Haiti',
                  'German DR',                      'Zaire',
                    'IR Iran',                    'Tunisia',
                       'Iran',                   'Cameroon',
                'New Zealand',                    'Algeria',
                   'Honduras',                     'Kuwait',
                       'Iraq',                    'Denmark',
                     'Canada',    'rn">Republic of Ireland',
   'rn">United Arab Emirates',                 'Costa Rica',
               'Saudi Arabia',                     'Russia',
                     'Greece',                    'Nigeria',
               'South Africa',                      'Japan',
                    'Croatia',                    'Jamaica',
                    'Senegal',                   'Slovenia',
                    'Ecuador',                   'China PR',
              'C�te d'Ivoire',             'Czech Republic',
                      'Ghana',                       'Togo',
                    'Ukraine',    'rn">Trinidad and Tobago',
  'rn">Serbia and Montenegro',                     'Angola',
                   'Slovakia',                     'Serbia',
 'rn">Bosnia and Herzegovina',                          nan]
Length: 84, dtype: str

In [93]:
#creating a copy of the dataset for further analysis

cleaned_dataset = matches.copy()

cleaned_dataset.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,4444.0,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,18346.0,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,24059.0,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,2549.0,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
4,1930.0,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,,23409.0,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA

In [94]:
cleaned_dataset.shape

(4572, 20)

In [95]:
cleaned_dataset = cleaned_dataset.dropna(how="all")

In [96]:
cleaned_dataset.shape

(852, 20)

In [97]:
cleaned_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 852 entries, 0 to 851
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  852 non-null    float64
 1   Datetime              852 non-null    str
 2   Stage                 852 non-null    str
 3   Stadium               852 non-null    str
 4   City                  852 non-null    str
 5   Home Team Name        852 non-null    str
 6   Home Team Goals       852 non-null    float64
 7   Away Team Goals       852 non-null    float64
 8   Away Team Name        852 non-null    str
 9   Win conditions        852 non-null    str
 10  Attendance            850 non-null    float64
 11  Half-time Home Goals  852 non-null    float64
 12  Half-time Away Goals  852 non-null    float64
 13  Referee               852 non-null    str
 14  Assistant 1           852 non-null    str
 15  Assistant 2           852 non-null    str
 16  RoundID               852 non-null    float64
 17  MatchID               852 non-null    float64
 18  Home Team Initials    852 non-null    str
 19  Away Team Initials    852 non-null    str
dtypes: float64(8), str(12)
memory usage: 133.3 KB

In [100]:
cleaned_dataset.columns

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials'],
      dtype='str')

In [104]:
cleaned_dataset.columns = cleaned_dataset.columns.str.strip()

cleaned_dataset.columns = cleaned_dataset.columns.str.replace(" ", "")
cleaned_dataset.columns = cleaned_dataset.columns.str.replace("-", "")

In [105]:
cleaned_dataset.columns

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'HomeTeamName',
       'HomeTeamGoals', 'AwayTeamGoals', 'AwayTeamName', 'Winconditions',
       'Attendance', 'HalftimeHomeGoals', 'HalftimeAwayGoals', 'Referee',
       'Assistant1', 'Assistant2', 'RoundID', 'MatchID', 'HomeTeamInitials',
       'AwayTeamInitials'],
      dtype='str')

In [107]:


cleaned_dataset['Year'] = cleaned_dataset['Year'].astype('Int64')

In [108]:
cleaned_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 852 entries, 0 to 851
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               852 non-null    Int64
 1   Datetime           852 non-null    str
 2   Stage              852 non-null    str
 3   Stadium            852 non-null    str
 4   City               852 non-null    str
 5   HomeTeamName       852 non-null    str
 6   HomeTeamGoals      852 non-null    float64
 7   AwayTeamGoals      852 non-null    float64
 8   AwayTeamName       852 non-null    str
 9   Winconditions      852 non-null    str
 10  Attendance         850 non-null    float64
 11  HalftimeHomeGoals  852 non-null    float64
 12  HalftimeAwayGoals  852 non-null    float64
 13  Referee            852 non-null    str
 14  Assistant1         852 non-null    str
 15  Assistant2         852 non-null    str
 16  RoundID            852 non-null    float64
 17  MatchID            852 non-null    float64
 18  HomeTeamInitials   852 non-null    str
 19  AwayTeamInitials   852 non-null    str
dtypes: Int64(1), float64(7), str(12)
memory usage: 134.1 KB

In [110]:
int_columns = [
    "HomeTeamGoals",
    "AwayTeamGoals"
]

cleaned_dataset[int_columns] = cleaned_dataset[int_columns].astype('Int64')

In [111]:
int_columns = [
    "HalftimeHomeGoals",
    "HalftimeAwayGoals"
]

cleaned_dataset[int_columns] = cleaned_dataset[int_columns].astype('Int64')

In [114]:
int_columns = [
    "RoundID",
    "MatchID",
    "Attendance"
]

cleaned_dataset[int_columns] = cleaned_dataset[int_columns].astype('Int64')

In [115]:
cleaned_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 852 entries, 0 to 851
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               852 non-null    Int64
 1   Datetime           852 non-null    str
 2   Stage              852 non-null    str
 3   Stadium            852 non-null    str
 4   City               852 non-null    str
 5   HomeTeamName       852 non-null    str
 6   HomeTeamGoals      852 non-null    Int64
 7   AwayTeamGoals      852 non-null    Int64
 8   AwayTeamName       852 non-null    str
 9   Winconditions      852 non-null    str
 10  Attendance         850 non-null    Int64
 11  HalftimeHomeGoals  852 non-null    Int64
 12  HalftimeAwayGoals  852 non-null    Int64
 13  Referee            852 non-null    str
 14  Assistant1         852 non-null    str
 15  Assistant2         852 non-null    str
 16  RoundID            852 non-null    Int64
 17  MatchID            852 non-null    Int64
 18  HomeTeamInitials   852 non-null    str
 19  AwayTeamInitials   852 non-null    str
dtypes: Int64(8), str(12)
memory usage: 139.9 KB

In [120]:
cleaned_dataset['HomeTeamName'] = cleaned_dataset['HomeTeamName'].replace({'USA': 'United States'})

cleaned_dataset['AwayTeamName'] = cleaned_dataset['AwayTeamName'].replace({'USA': 'United States'})

In [121]:
uniqueCountries = cleaned_dataset['HomeTeamName'].unique()
print(uniqueCountries)

<StringArray>
[                    'France',              'United States',
                 'Yugoslavia',                    'Romania',
                  'Argentina',                      'Chile',
                    'Uruguay',                     'Brazil',
                   'Paraguay',                    'Austria',
                    'Hungary',                'Switzerland',
                     'Sweden',                    'Germany',
                      'Spain',                      'Italy',
             'Czechoslovakia',                       'Cuba',
                    'England',                 'Germany FR',
                     'Turkey',               'Soviet Union',
           'Northern Ireland',                     'Mexico',
                      'Wales',                   'Portugal',
                  'Korea DPR',                       'Peru',
                    'Belgium',                   'Bulgaria',
                  'German DR',                      'Zaire',
                     'Poland',                  'Australia',
                   'Scotland',                'Netherlands',
                      'Haiti',                    'Tunisia',
                    'Algeria',                   'Honduras',
                     'Canada',                    'Morocco',
             'Korea Republic',                       'Iraq',
                    'Denmark',   'rn">United Arab Emirates',
                 'Costa Rica',                   'Cameroon',
    'rn">Republic of Ireland',                   'Colombia',
                     'Norway',                    'Nigeria',
               'Saudi Arabia',                    'Bolivia',
                     'Russia',                     'Greece',
                    'Jamaica',               'South Africa',
                      'Japan',                    'Croatia',
                   'China PR',                    'Senegal',
                   'Slovenia',                    'Ecuador',
    'rn">Trinidad and Tobago',  'rn">Serbia and Montenegro',
                     'Angola',             'Czech Republic',
                       'Togo',                       'Iran',
              'C�te d'Ivoire',                      'Ghana',
                    'Ukraine',                     'Serbia',
                'New Zealand',                   'Slovakia',
                    'IR Iran', 'rn">Bosnia and Herzegovina']
Length: 78, dtype: str

In [123]:
cleaned_dataset.head()

,Year,Datetime,Stage,Stadium,City,HomeTeamName,HomeTeamGoals,AwayTeamGoals,AwayTeamName,Winconditions,Attendance,HalftimeHomeGoals,HalftimeAwayGoals,Referee,Assistant1,Assistant2,RoundID,MatchID,HomeTeamInitials,AwayTeamInitials
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,United States,3,0,Belgium,,18346,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA

In [130]:
import pandas as pd

cleaned_dataset['Datetime'] = pd.to_datetime(cleaned_dataset['Datetime'], format='%d %b %Y - %H:%M', errors='coerce')

cleaned_dataset[cleaned_dataset['Datetime'].isnull()]

cleaned_dataset['MatchDate'] = cleaned_dataset['Datetime'].dt.date
cleaned_dataset['MatchTime'] = cleaned_dataset['Datetime'].dt.time

In [131]:
cleaned_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 852 entries, 0 to 851
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               852 non-null    Int64
 1   Datetime           842 non-null    datetime64[us]
 2   Stage              852 non-null    str
 3   Stadium            852 non-null    str
 4   City               852 non-null    str
 5   HomeTeamName       852 non-null    str
 6   HomeTeamGoals      852 non-null    Int64
 7   AwayTeamGoals      852 non-null    Int64
 8   AwayTeamName       852 non-null    str
 9   Winconditions      852 non-null    str
 10  Attendance         850 non-null    Int64
 11  HalftimeHomeGoals  852 non-null    Int64
 12  HalftimeAwayGoals  852 non-null    Int64
 13  Referee            852 non-null    str
 14  Assistant1         852 non-null    str
 15  Assistant2         852 non-null    str
 16  RoundID            852 non-null    Int64
 17  MatchID            852 non-null    Int64
 18  HomeTeamInitials   852 non-null    str
 19  AwayTeamInitials   852 non-null    str
 20  MatchDate          842 non-null    object
 21  MatchTime          842 non-null    object
dtypes: Int64(8), datetime64[us](1), object(2), str(11)
memory usage: 153.2+ KB

In [133]:
cleaned_dataset.head()

,Year,Datetime,Stage,Stadium,City,HomeTeamName,HomeTeamGoals,AwayTeamGoals,AwayTeamName,Winconditions,...,HalftimeAwayGoals,Referee,Assistant1,Assistant2,RoundID,MatchID,HomeTeamInitials,AwayTeamInitials,MatchDate,MatchTime
0,1930,1930-07-13 15:00:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,...,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX,1930-07-13,15:00:00
1,1930,1930-07-13 15:00:00,Group 4,Parque Central,Montevideo,United States,3,0,Belgium,,...,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL,1930-07-13,15:00:00
2,1930,1930-07-14 12:45:00,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,...,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA,1930-07-14,12:45:00
3,1930,1930-07-14 14:50:00,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,...,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER,1930-07-14,14:50:00
4,1930,1930-07-15 16:00:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,...,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA,1930-07-15,16:00:00

In [136]:
import pandas as pd

cleaned_dataset.to_csv("../Data/cleaned/WorldCupMatches_C.csv", index=False)